### ISSUE TITLE
Comprar material

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#13]
- 4 ou 5 raspberry pi 2 model B + 2 que ya tenemos en GPUL
- 30-40 raspberry pi zero (si es posible)
- 5 adaptadores HDMI/VGA
- 5 cargadores
- 5 tarxeta de memoria 8 gigas polo menos
- Sensores (a definir)
- Punteiro laser para pasar as diapos

**Comment by castrinho8** [comment]
@braisarias

**Comment by braisarias** [comment]
Mandado correo a Oscar de BricoGeek para ver se nos pode facer un desconto ou se lle interesaría participar como sponsor.

**Comment by castrinho8** [comment]
Ping a isto @braisarias

**Comment by braisarias** [comment]
Non me contestou ao correo que tiña eu del, pero hoxe Alejo deume outro correo del, a ver se nese contesta. Senón mércanse onde sexa e listo.

**Comment by braisarias** [comment]
Parte xa chegou o venres e o resto chega hoxe (luns). Ao final o que merquei foi o que era preciso para a charla 2:
6 Raspberry's
10 adaptadores
10 tarxetas
15 sensores Hall
5 sensores PIR

**Comment by braisarias** [comment]
O que comentei arriba, xa está todo en GPUL
