### ISSUE TITLE
Preparar plataforma para inscribirse (indico)

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#21]
Escoller unha plataforma para realizar a inscrición

**Comment by ssaavedra** [comment]
De momento eu estou facendo un portal para inscribirse en PHP. Está en http://github.com/gpul-org/labs-registrar/

**Comment by ssaavedra** [comment]
A idea é poder pagar por PayPal ou indicar que se vai a facer/se fixo transferencia bancaria.

**Comment by castrinho8** [comment]
Finalmente decidíuse utilizar o https://www.gpul.org/indico para isto
