### ISSUE TITLE
Preparar plataforma de discusión

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#23]
Crear un foro ou chat no que manter relación entre a xente que participe no proxecto.
Igual un http://www.discourse.org/

**Comment by ssaavedra** [comment]
Estamos niso, tratando de poñer un Discourse no servidor.

Actualmente temos un problema ao intentar crear a imaxe (./launcher bootstrap app) seguindo as propias instruccións de discourse, co cal non está sendo todo tan sinxelo como debería (que non o entendo, ao final trátase de crear unha imaxe de Docker).

O que puiden ver que pasa é o seguinte:

``` text
I, [2016-01-19T18:44:02.464635 #37]  INFO -- : > echo "done configuring web"
I, [2016-01-19T18:44:02.466800 #37]  INFO -- : done configuring web

I, [2016-01-19T18:44:02.468279 #37]  INFO -- : > cd /var/www/discourse && gem update bundler
ERROR:  While executing gem ... (ArgumentError)
    IPv6 address must be 16 bytes
I, [2016-01-19T18:44:02.749699 #37]  INFO -- : Updating installed gems

I, [2016-01-19T18:44:02.750027 #37]  INFO -- : Terminating async processes
I, [2016-01-19T18:44:02.750060 #37]  INFO -- : Sending INT to HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/9.3/bin/postmaster -D /etc/postgresql/9.3/main pid: 66
I, [2016-01-19T18:44:02.750096 #37]  INFO -- : Sending TERM to exec chpst -u redis -U redis /usr/bin/redis-server /etc/redis/redis.conf pid: 194
2016-01-19 18:44:02 UTC [66-2] LOG:  received fast shutdown request
2016-01-19 18:44:02 UTC [66-3] LOG:  aborting any active transactions
2016-01-19 18:44:02 UTC [73-2] LOG:  autovacuum launcher shutting down
194:signal-handler (1453229042) Received SIGTERM scheduling shutdown...
2016-01-19 18:44:02 UTC [70-1] LOG:  shutting down
194:M 19 Jan 18:44:02.800 # User requested shutdown...
194:M 19 Jan 18:44:02.800 * Saving the final RDB snapshot before exiting.
194:M 19 Jan 18:44:02.863 * DB saved on disk
194:M 19 Jan 18:44:02.863 # Redis is now ready to exit, bye bye...
2016-01-19 18:44:02 UTC [70-2] LOG:  database system is shut down


FAILED
--------------------
RuntimeError: cd /var/www/discourse && gem update bundler failed with return #<Process::Status: pid 290 exit 1>
Location of failure: /pups/lib/pups/exec_command.rb:105:in `spawn'
exec failed with the params {"cd"=>"$home", "hook"=>"web", "cmd"=>["gem update bundler", "chown -R discourse $home"]}
145178f060e7d85826e487eb17b2c20b6d4fac78b75d453cb1bb3adae36e0467
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one
```

E non hai ningún outro erro anterior, así que eu vexo que o erro ten que estar ao facer gem update bundler, e iso non tiña sentido que fallase, tendo ademais en conta que tería que vir na imaxe de Discourse.

**Comment by rcoedo** [comment]
`ERROR:  While executing gem ... (ArgumentError) IPv6 address must be 16 bytes`. ¿Podría ser un problema de red? Quizás por como está configurado el host docker.

¿Qué opinas?

**Comment by ssaavedra** [comment]
Interesante o que dis. Que o erro non ten moito sentido per se (unha IPv6 ten que ter 16 bytes, obviamente).

A máquina host está configurada e responde tanto por IPv4 como por IPv6 (polo que puiden probar empregando outra máquina que comparte os dous primeiros bytes de dirección IPv6).

Os contenedores Docker obteñen tamén tanto IPs IPv4 de direccionamento privado (dentro de 172.16.0.0/12) como IPv6 link-local (fe80::/64).

Se podedes, comprobade se a vós vos funciona crear a imaxe de Discourse seguindo as súas instruccións (clonando o repo git de [discourse/discourse_docker](//github.com/discourse/discourse_docker) , copiando `samples/standalone.yml` a `containers/app.yml` e executando `./launch boostrap app`.

**Comment by ssaavedra** [comment]
Parece que non cae.

https://forums.gpul.org/t/benvidos-todos-aos-gpul-labs/20

**Comment by ssaavedra** [comment]
Porqué o reopen?

**Comment by castrinho8** [comment]
A columna de "Done" no waffle solo mostra as actividades pechadas a semana pasada e igual estaba ben poder ver todas as que imos pechando, non? Por se hay confusións ou se quere volver a algunha sen ter que ir ata Github.

E por iso que creei artificialmente unha columna de "Finished" para sustituir a "Done" co seu Tag propio de "finished", non sei se é boa idea ou non pero non se me ocurríu outra solución

**Comment by ssaavedra** [comment]
Eu creo que non, se están xa están. A idea dun xestor de tarefas é ver o que hai por facer, máis ca o que se fixo :)

**Comment by castrinho8** [comment]
Certo é, unico por se hay algo que puxeches en done sen darte conta e tes que volve a traelo, que igual tes que ir a github a por el xd
Pero como vexas, se tal volveo poñer como estaba ;)

**Comment by ssaavedra** [comment]
Quedar queda un pouco raro. E en GitHub queda raro que non se pechen as issues.
