### ISSUE TITLE
Actualizar web

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#24]
Meter:
- Fotos de voluntarios
- Links a github
- Dossier de patrocinio
- Link a plataforma de discusión
- Reconocimientos
  - Logo: <a href="http://www.freepik.com/free-photos-vectors/background">Background vector designed by Freepik</a>

Quitar:
- Apartado de voluntarios

**Comment by castrinho8** [comment]
Solo falta:
- Subir dossier de patrocinio
- Link al discourse
- Links a registros

**Comment by castrinho8** [comment]
Preparada para deploy, si tes 5 mins nalgún momento @ssaavedra ;)

**Comment by ssaavedra** [comment]
Volve a abrir aquí se fas algún cambio, e _asígnama_ :-)
