### ISSUE TITLE
Charla 1: Buscar poñente (Python, git, GitHub)

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#27]
Intro python + git + github

**Comment by ssaavedra** [comment]
@franrua @BreixoCF, as issues estas teñen o problema de que non se poden asignar a máis dunha persoa (shame on you, GitHub).
Así que para deixar máis claro eso están os comentarios :-)

Se precisades unha indicación de por onde preparar a actividade podemos debatilo noutra issue (así esta queda por se hai algún cambio de última hora cos ponentes, e reabrila se alguén non poida vir ou algo así).

Se vedes que non respondo, facédeme ping mencionándome (escribides nalgunha parte do texto @ssaavedra ) e así no caso de que non estea monitorizando a conversa xa me chega igual a notificación.
