### ISSUE TITLE
Charla 2: Buscar poñente

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#28]
Raspberry Pi

**Comment by braisarias** [comment]
Estou eu niso en Bricolabs, a ver se Xoan Sampaiño se apunta

**Comment by pedrovr-** [comment]
Yo toqué a Ruben Hortas pero me dijo que no podía prepararla, así que nada

**Comment by ResonantWave** [comment]
Me presento como voluntario para dar esta charla

**Comment by castrinho8** [comment]
Genial, estamos pendientes de Xoan y de @pepdiz y en función de eso vemos.
Lo que le comentaba a @pepdiz, que la idea es hacer unas **charlas principales** entre las que estará esta (1 cada semana) y luego añadir alguna digamos que no sea tan **Core** para el proyecto y en las que podría entrar una que sea un poco más concreta de Raspberry o de algo que sea más transversal a la idea inicial ;)

**Comment by castrinho8** [comment]
Finalmente es posible que Xoan realice otra actividad por lo que o bien @pepdiz o @ResonantWave podríais dar este taller si os va bien ;)
La idea es enseñar un poco como hacer un programa en Python para acceder a la GPIO y leer datos de un sensor y luego que sean los asistentes los que se pongan a cacharrear y a probar ellos, incluso con varios sensores si da tiempo.
¿Cómo lo veis?

**Comment by ResonantWave** [comment]
Lo veo perfecto. Había pensado hacer una mini introducción a las distintas librerías para usar desde python, y después hacer parpadear un led para pillar las nociones más básicas. Tras esto, usar varios sensores de distintos protocolos como i2c, spi o incluso 1-wire. Creo que podría dar tiempo de sobra para todo.

**Comment by castrinho8** [comment]
pues perfecto, te la asignamos entonces a ti ;)
Te va bien la fecha? Miercoles 17 a partir de las 5 por ejemplo?

**Comment by ResonantWave** [comment]
Sin problemas! Debería abrir otro issue para discutir el contenido de la charla?

**Comment by castrinho8** [comment]
Puede estar bien, yo la verdad no tengo mucha idea de trabajar con la Raspberry pero fijo que alguien puede aportar cosas interesantes ;)
