### ISSUE TITLE
Charla 3: Buscar poñente (Git avanzado)

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#29]
Git avanzado y code review

**Comment by carlisgg** [comment]
nesta teño o poñente perfecto, se queredes falo con el a ver se se pode achegar ata coruña. Temos algún recurso para invitalo a comer ou pagarlle un tren?

**Comment by castrinho8** [comment]
Xenial, polos recursos non hay problema, igual para unha mariscada non da pero... jeje
Que poñente é por certo? ;)

**Comment by carlisgg** [comment]
pois estaba pensando en Pepe Doval @pepellou que xa fixo varios obradoiros de git avanzado e controla de code review...

**Comment by castrinho8** [comment]
Xenial, pois por min perfecto ;)
A idea é comezar coa primeira charla a 1º ou 2º semana de Febreiro e a partir de ahi unha semanal.

**Comment by pepellou** [comment]
Tedes sorte: non me gusta o marisco ;-)

Estarei atento a que me digades cando e onde teño que estar.

**Comment by castrinho8** [comment]
Así da gusto :) Ímolo comentado logo, vou actualizando as tarefas

**Comment by castrinho8** [comment]
Boas de novo @pepellou, ¿que tal che vai como data o 24 de Febreiro pola tarde?

**Comment by pepellou** [comment]
Vaime perfecto, sempre que poda chegar ao último tren de volta (22:10).

**Comment by castrinho8** [comment]
Sin problema, se che parece ben podemos comezar sobre as 17:00 e veste comer pola Coruña ;)

**Comment by pepellou** [comment]
Perfecto.
