### ISSUE TITLE
Charla 4: Buscar poñente (Metodologías ágiles)

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#30]
Scrum/metodologías ágiles

**Comment by carlisgg** [comment]
esta a podería dar eu ou alguen que coñeza da comunidade sen problema...

**Comment by carlisgg** [comment]
se vos parece, claro.

**Comment by castrinho8** [comment]
Adiante! ;)

**Comment by castrinho8** [comment]
@carlisgg vaiche ben o día 2 de marzo sobre as 17:30?

**Comment by castrinho8** [comment]
@carlisgg que opinas de meter o logo de árticos, pop sports ou o de agile galicia na web como colaborador e como publi na charla?

**Comment by carlisgg** [comment]
pois a min paréceme xenial, o de articos e agile galicia coido que teñen máis sentido nesta charla..

**Comment by carlisgg** [comment]
vaime ben o dous de marzo, se o queredes facer definitivo xa o apunto na axenda

**Comment by castrinho8** [comment]
pechado queda, maña poñovos os logos ;)
