### ISSUE TITLE
Charla 5: Buscar poñente (Django Framework)

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#31]
Django Framework

**Comment by braisarias** [comment]
Falei con Uxío, e apuntase a dar esta charla.
Uxío deu formación na Academia Postal de Python (non sei se de Django).
Seguro que o fai ben.
Comentamos de ser o 9 ou o 16 de marzo.
Faleille do proxecto global, tamén por se lle podía dar algún enfoque orientado.

Quedamos de ir falando, para ir concretado máis cousas

**Comment by alejopj** [comment]
Boas. Eu comenteillo tamén a Sobrino por se se apuntaba. Xa lle dixen que se pasase por aquí. ;)

**Comment by alejopj** [comment]
Sobrino non está dispoñible que seica anda emigrado, xD.
