### ISSUE TITLE
Charla 6: Buscar poñente (APIs RESTful)

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#32]
APIs RESTful

**Comment by girianshido** [comment]
Estaría ben poñer RESTful. Na charla estaría guay dar unha introducción aos distintos tipos de formas de API (SOAP, RPC, REST), a evolución das APIs na historia de Internet, arquitecturas REST vs RESTful, e nomear os diferentes niveis descritos no [Modelo de Madurez de Richardson](http://restcookbook.com/Miscellaneous/richardsonmaturitymodel/).

Fora a un seminario do CNTG de [@agustincl](https://twitter.com/agustincl) que a pesar de que trataba sobre a creación dunha API en PHP, tamén falou da historia das APIs, sobre a tese de Roy Fielding (co-fundador de Apache Fundation) e a evolución das APIs cara HATEOAS e formatos coma HAL-JSON. Recoméndovos botarlle un olla ás súas [slides](http://learnsqr.github.io/apification/).

Sobre o desenvolmento na charla non sei se irá orientado a seguir a liña de creación da API con Django. Se non é así, e non hai ninguén eu poderíame ofrecer como poñente a dala con [Spring Data REST](http://projects.spring.io/spring-data-rest/), [Spring HATEOAS](http://spring.io/guides/gs/rest-hateoas/) ou co xerador de [JHipster](https://github.com/jhipster/generator-jhipster)

**Comment by ssaavedra** [comment]
A arquitectura é REST [[[1](http://stackoverflow.com/questions/1568834/whats-the-difference-between-rest-restful)]](http://stackoverflow.com/questions/1568834/whats-the-difference-between-rest-restful). Estaría ben facer iso que di @dalbelap. Respecto do tema de API con Django, hai un plugin, o django-rest-framework [[[2](http://www.django-rest-framework.org)]](http://www.django-rest-framework.org), que, evidentemente, é un API RESTful. Respecto a HATEOAS, o plugin toma poucas decisións [[[3](http://www.django-rest-framework.org/topics/rest-hypermedia-hateoas/)]](http://www.django-rest-framework.org/topics/rest-hypermedia-hateoas/) pero pódese facer un api suficientemente hipercomunicada (os modelos xa soportan out-of-the-box referenciarse por URIs en lugar de por ids, e o que pode que habería que facer é a parte de autodescubrimento, que sería enviar ao cliente as urls ás accións que pode realizar co contido: iso sí que non está feito creo [ou é un plugin que non coñezo]).

**Comment by alejopj** [comment]
Boas.

Tal e como comentaba pola rolda de correo, ofrézome voluntario para dar esta charla.

Contando con que vaiamos a charla por semana, entendo que esta sería para dar o 16 de marzo, xusto antes de Semana Santa.

A hora aínda non vola podo confirmar, dado que aínda queda un mes e teño que comentalo antes no traballo. No peor dos casos, sería para as 18:30 (saio ás 18:00). Pero polo que vexo veñen poñéndose todas para as 17:30, así que tentarei que me deixen saír un pouco antes. De tódolos xeitos, son eu só e non conto extenderme moito, así que aínda empezando ás 18:30 rematariamos a unha hora prudente.

Aínda que de momento non hai poñente para a de Django, entendo que a de REST iría despois si ou si. Así que non teño pensado pararme en Django en si, senón na parte REST do framework.

Entre as fontes que teño en mente empregar están as seguintes:

http://restcookbook.com/
http://www.restapitutorial.com/
https://www.djangoproject.com/
http://www.django-rest-framework.org/

Algunha delas xa a mencionou @dalbelap (modelos de madurez, HATEOAS, etc.), pero a maioría dos conceptos avanzados comentareinos máis ben por enriba, exceptuando a securización (OAuth2, JWT), onde me pararei un pouco máis.

A idea principal é que comprendan o que é unha APi REST, para que se emprega e como se crea unha básica dende cero. Se saen con isto claro da charla xa me dou por contento.

Tamén tiña pensado aproveitar para comentar por enriba algún editor recomendable para Python (NinjaEdit, PyCharm, PyDev -o que vou empregar-) e algunha ferramenta para control de versións (GitEye) en caso de que o editor non teña ou prefira empregarse unha externa.

Se tedes xa unha idea da funcionalidade que queredes darlle á RasPi, podo ver de sacar algún caso de uso e facer algún exemplo máis concreto.

E iso é máis ou menos todo o que teño en mente polo de agora. Xa me dicides co que sexa.

**Comment by castrinho8** [comment]
Pola hora non te preocupes que temos reservado ata as 21:30 se fai falta :P

As datas estaría ben o 16 de marzo se conseguimos un poñente para Django a semana anterior, en caso contario podería retrasarse sen problema ata a semana seguinte a semana santa.

Por funcionalidade acéptanse suxerencias de todos os presentes jeje

**Comment by girianshido** [comment]
Xenial @alejopj :smiley:
