### ISSUE TITLE
Pedir pegatinas a Github

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#33]
Escribir a Github diciendo que somos una asociacion y tal a ver si nos mandan unas pegatinas gratis ;)

**Comment by ResonantWave** [comment]
Se podría también escribir a la FSFE, y pedir su habitual pack de pegatinas, trípticos y pósters. Formulario [aquí](https://fsfe.org/contribute/spreadtheword.en.html).

**Comment by castrinho8** [comment]
Buena idea pero de esos pedimos para el document freedom day el año pasado y creo que aún hay algunas pegatas y flyers por el despacho pero puede ser tb buena idea

**Comment by ssaavedra** [comment]
Tarde? Ou dámoslle para adiante a isto?

**Comment by castrinho8** [comment]
Xa teño un mail preparado, solo falta acabar de traducir o dossier de sponsors para mandalo tamén, igual hay sorte e patrocinan de algunha forma :P
