### ISSUE TITLE
Charla 8: Buscar poñente (ReactJS)

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#34]
Aquí ofrézome eu e tamén Roman comentóu de montar el unha, igual podemos facer unha de intro e outra avanzada ou algo de JS tamén ;)

**Comment by rcoedo** [comment]
Cuenta conmigo para lo que haga falta :+1:

**Comment by davidbarral** [comment]
Buenas, hemos hablado con Pablo y la gente de Trabe, @asischao, @rcoedo y un servidor podemos dar un par de charlas de React + Redux que es algo que estamos usando en nuestros proyectos. Serían dos introducciones. La primera de ES6+React y la segunda de Redux+React. 

En principio 2 horas para cada una (más el descanso) deberían bastar. 

En la primera charla hablaríamos de las novedades de ES6 y cómo usarlo con Babel y luego lo básico de REACT 0.15(15) y cómo aprovechar la sintáxis de ES6.

En la segunda charla hablaríamos de Redux (conceptos y eso), como engancharlo con React y cómo aprovechar las herramientas.

Se aceptan comentarios y sugerencias :)

Las fechas que manejabamos eran 30 de Marzo y 6 de Abril.

**Comment by castrinho8** [comment]
Imagino chicos que no habrá problema para que pongamos el logo de Trabe en la web como partner por venir a dar la charla, verdad? ;)

**Comment by davidbarral** [comment]
Ningún problema. Te adjunto unos logo en calidad por si no lo teneís para que podáis escalarlo al gusto :) 
![logo_trabe_horizontal](https://cloud.githubusercontent.com/assets/8909/13468980/a09d89a2-e0a5-11e5-8f5f-9b08b2c42e1a.png)
![logo_trabe_vertical](https://cloud.githubusercontent.com/assets/8909/13468981/a09f7636-e0a5-11e5-9edb-ad05dc388ef7.png)

**Comment by castrinho8** [comment]
Por cierto chicos, estabamos pensando en poner los carteles de la primera charla este miércoles ya que luego viene semana santa y coincide justo en medio e igual los ve poca gente.
Es por eso que quería pediros a ver si podéis pasarme un título y un resumen corto de lo que vais a contar, con un par de frases llegaría bien y algo del ponente/ponentes, también 1 linea o así.
Sería algo tipo lo que tenemos [aquí](https://www.gpul.org/indico/categoryDisplay.py?categId=2)

Graciñas!

**Comment by davidbarral** [comment]
Ok. Lo hablamos ahora y te decimos algo en breve :)

**Comment by davidbarral** [comment]
Hola,

como no tenemos cerrado el contenido, te mando unas descripciones escuetas:

"ES6, Babel y ReactJS"
Novedades de ES6 (o ES2015) y cómo utilizar Babel para empezar a utilizarlo en proyectos. ReactJS como librería de UI de aplicaciones y cómo aprovechar ES6 para desarrollar nuestro código React.

"Redux y ReactJS".
Introducción a la librería Redux, un contenedor de estado predecible para desarollo de aplicaciones Javascript: cómo funciona, qué ventajas y herramientas aporta, y cómo integrarlo con ReactJS. 

En cuanto a los ponentes, aun no nos las hemos repartido entre nosotros así que puedes ponernos a los tres (Asís García, Román C. Coedo y David Barral) o bien un lacónico Trabe Soluciones :smiley:

**Comment by castrinho8** [comment]
Perfecto, anoto todo entonces, graciñas :)
