### ISSUE TITLE
Definir onde realizar discusións (FAQ/dúbidas)

### ISSUE THREAD

**Issue by ssaavedra** [gpul-labs/roadmap#36]
Estamos pendentes de #23 pero será preciso definir onde realizar discusións, se a dependencia non fructifica, noutro sistema.

Eu propoño como failsafe usar issues noutro repo aquí (gpul-labs/preguntas ou algo así) e empregar a wiki para enlazar as contestadas nas issues.

**Comment by castrinho8** [comment]
A min paréceme boa idea se non se amaña o da #23

**Comment by ssaavedra** [comment]
Xa está #23 finalizado, pódense plantexar as cousas alí.
