### ISSUE TITLE
Propoñer unha recomendación para a licencia da documentación

### ISSUE THREAD

**Issue by ssaavedra** [gpul-labs/roadmap#37]
Esto foi orixinalmente falado en #35 e sería bo ter unha recomendación xeral para os poñentes de liberar a súa documentación cunhas directrices, salvo que teñan outras ideas ou usos específicos do contido exposto.

Esta é a miña proposta:
# Sobre a documentación

A documentación, eu creo que Wikipedia xa tomou esa decisión dun xeito acertado hai tempo coa doble licencia:

```
Licencia Creative Commons Atribución-CompartirIgual 3.0 Unported ("CC BY-SA"), y
Licencia de Documentación Libre de GNU ("GFDL") (sin versionar, sin secciones, textos de tapa o contratapa invariantes).
```

Nós podemos subir a CC-BY-SA á 4.0 International, xa que non temos texto antiguo que non poidamos portar.
## Sobre os exemplos de código da documentación

Se o software son exemplos pequenos (menos de 10 liñas: o tipo de cousas que poñerías nunhas transparencias) eu diría que o código se liberase baixo [CC0][CC0], porque en realidade é imposible verificar se existe unha infracción de copyright.
# Sobre o código fonte de exemplo

Se os exemplos non son moi substanciais, refírase ao parágrafo anterior.

Agora, respecto a código fonte de programas de exemplo un pouco extensos, posiblemente suxeitos a ser _copyrightable_s, non teño unha recomendación clara.

 É habitual ver que código fonte de exemplo licenciado con licencias libres non-copyleft (exemplos: documentación de emprego de APIs de empresas, por exemplo en developers.google.com; repos de exemplo en GitHub sobre proxectos libres non-copyleft...). Como licencia non-copyleft eu poñería, ou ben MIT (por ser sinxela de entender) ou Apache 2 (polas amplas garantías de reutilización).

Por suposto se nalgún caso o software é GPL, os exemplos de código tamén deberían de selo, pois o software GPL non pode linkarse con calquera outra licencia arbitraria

Tamén pode optarse porque tódolos exemplos sexan GPLv3 e a documentación, GFDL.

Que opinades, @gpul-labs/coordinacion ?

**Comment by ssaavedra** [comment]
@txenoo ti que opinas?

**Comment by castrinho8** [comment]
E penso que está ben o que propós e a [FSF propón a Apache 2](http://www.gnu.org/licenses/license-list.es.html#GPLCompatibleLicenses) mellor ca MIT e é compatible coa GPL 3 asique igual esta ben poñela e listo (Se vemos que hay algunha GPL 2 nun caso concreto cambiamola e listo ;)

Se podes @ssaavedra , pon a decisión que tomemos na [páxina da wiki](https://github.com/gpul-labs/roadmap/wiki/Venir-como-ponente)

**Comment by ssaavedra** [comment]
Xa está; en https://github.com/gpul-labs/roadmap/wiki/Licencias-sugeridas .
