### ISSUE TITLE
Enviar dossier de patrocinio

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#40]
E ter unha lista de entidades as que enviarllo

**Comment by braisarias** [comment]
Eu adianteime e envieillo a Bricogeek, de paso que lle comentei se nos facía un desconto nas raspberry.

**Comment by castrinho8** [comment]
Por certo, xa se mandou isto a algunhas empresas do mundo tecnolóxico. Acéptanse suxerencias, igual incluso de empresas non tecnolóxicas

**Comment by brainsqueezer** [comment]
En Bigpress ( http://bigpress.net ) de momento seguro no nos lo podemos permitir pero nos interesa ir conociendo como se podrían hacer cosas para ver si para el año o dentro de dos podremos. Aparte se lo podemos mostrar a otros con más capital que nosotros. Correo: info@bigpress.net

**Comment by castrinho8** [comment]
Genial @brainsqueezer, ya os lo hemos enviado, muchas gracias por el interés y la difusión ;)
