### ISSUE TITLE
Charla git avanzado: planificación

### ISSUE THREAD

**Issue by pepellou** [gpul-labs/roadmap#42]
## Contidos

Estiven lendo #35 para facerme idea do que se vai introducir de git antes da miña charla.
Polo que entendo, eu tería que cubrir, como mínimo: `checkout`, ramas, conflictos e pull requests.
Ademais deses, gustaríame saber a vosa opinión sobre que contidos vos parecen máis interesantes, por exemplo: tags, rebases, bisects, hooks, etc.
Eu teño [aquí](https://github.com/pepellou/CursoGit/blob/master/temario.markdown) un temario que preparei hai tempo para outro curso de git. Se vedes algo aí que pensedes que é imprescindible incluír, _please tell me_ :relaxed: 
## Operativa

Onde deixo material?
Eu son máis de preparar exemplos de código que transparencias, para que sexa o máis práctico posible. Entendo que se unha das ideas dos labs é que o material acabe compartido para que calquera o poda ver despois, sería interesante que faga tamén transparencias, ¿si?

Canto dura o taller? Hai algún descanso planificado?

**Comment by rafbermudez** [comment]
Gústame a idea de incluír boas prácticas. E os tags e rebases, tamén.

Personalmente son fan do Feature Branch Workflow facendo rebases

**Comment by castrinho8** [comment]
+1 tamén ao que di @rafbermudez

Eu penso que si que os checkouts, ramas, conflictos e pull requests estaría ben tocalos e comentar algo de cómo facer code review ;)
Incluso se dese tempo a falar de tags ou rebases para reescribir commits molaba tamén (a min persoalmente é unha utilidade que utilizo moito).

Na **operativa**, penso que vai perfecto utilizar códigos de exemplo e facer todo bastante práctico, o que si sería ideal é telos máis ou menos ordenados para que a xente que non asista, poida ir entendendo o que se fixo (máis ou menos, tamén teremos o video para axudar)

A duración como moito pode ser de 16 a 21 pero penso que igual sería bon non pasar das 3/4 horas que incluirán un descanso tamén polo medio (ou 2 según prefiras ti)

**Comment by ssaavedra** [comment]
> Onde deixo material?
> Eu son máis de preparar exemplos de código que transparencias, para que sexa o máis práctico posible. Entendo que se unha das ideas dos labs é que o material acabe compartido para que calquera o poda ver despois, sería interesante que faga tamén transparencias, ¿si?

Deberías de poder crear repos nesta org. Se non podes, dime o nome do(s) repo(s) e creámolos e dámosche permiso neles. Se precisas outro tipo de almacenamento, se podes subilo á sección de Descargas do propio repo, fantástico, e senón escríbenos de novo e artellamos algún xeito de aloxalo na nosa infraestrutura.

O que sí che pedimos é que os exemplos e a documentación sexan postos a libre disposición cunha licencia libre (ver #37).

Respecto á duración, o que di @castrinho8 de non pasarse de 4 horas secúndoo, e se queres que teña esa extensión (por exemplo de 17:00 a 21:00) eu diríache que o plantexes como de 3,5 h como moito, e facerlle un ou dous descansos para refrescar a cabeza, tanto a ponente como a asistentes, e así tamén da lugar a unha discusión e preguntas máis informais na cafetería (ou onde sexa) ;-)

**Comment by pepellou** [comment]
Ok, chicos, grazas polas respostas.
A ver se esta semana deixo listo un guión.

**Comment by castrinho8** [comment]
Boas de novo @pepellou ;)
Estiven pensando en ver que vos parecería poñer o logo de SetPay na web dos labs como colaborador e na publicidade da charla? Que opinas?

**Comment by pepellou** [comment]
Pois o do logo parécenos xenial ^_^

Un par de cuestións, por outra banda:
- Como canta xente terei no taller?
- Terán xa entre mans algún proxecto co que probar cousas de git?

**Comment by castrinho8** [comment]
Perfecto.

En principio o lab ten para 36 postos sentados con mesa e igual podemos ter 4 ou 5 mais sen mesa ;)
En principio non teñen nada preparado oficialmente, pero se che parece boa idea igual se pode pensar en montar algo
