### ISSUE TITLE
Charla 2: Contenidos y materiales

### ISSUE THREAD

**Issue by ResonantWave** [gpul-labs/roadmap#49]
Abro esta issue para comentar los contenidos de la segunda charla, sobre Raspberry Pi.

Yo había pensado seguir los siguientes puntos:
- ¿Qué es una Raspberry Pi?
- La fundación Raspberry Pi y su misión.
- Comparación respecto a un ordenador «normal».
- Aprender a instalar un SO y manejo básico del sistema. (primera práctica)
- Iniciación al GPIO:
  - Descripción general.
  - Descripción de los distintos protocolos soportados.
- Utilizar la librería WiringPi para trastear desde la cli con los GPIO y encender/apagar un led. (segunda práctica)
- Mini introducción a python para aquellos que no asistieron a la primera charla, y para refrescar brevemente.
- Enumeración de las distintas librerías del GPIO para Python (RPi.GPIO, GPIO Zero...).
- Tercera práctica: hacer parpadear un LED, probando a modificar tiempos y demás, utilizando Python.
- Descripción de las entradas de la Pi. Diferencia entre entrada analógica y digital. 
- Cuarta práctica: Leer el estado de un botón (pulsado/sin pulsar).
- Quinta práctica: Leer sensores como por ejemplo PIRs o sensores de efecto Hall.
  Por último, y si el tiempo llegase, podría realizarse una sexta práctica, para combinar entradas y salidas. Por ejemplo, al detectarse movimiento con el PIR, hacer que se encienda un LED.

Los materiales necesarios serían una Pi para cada persona (o dos, en caso de ser necesario), incluyendo teclado, ratón (para el manejo básico del sistema inicial), pantalla...
A mayores, un par de LEDs por cada Pi, y un PIR o sensor Hall digital. Para la parte de leer el estado de un botón, una placa de pruebas como [esta](http://ecx.images-amazon.com/images/I/51HxRQ33atL.jpg) sería interesante. Los botones en sí puedo ponerlos yo.

**Comment by braisarias** [comment]
Sobre o material, servirianche estos PIR:
http://es.aliexpress.com/item/Free-Shipping-10PCS-SR501-HC-SR501-Adjust-IR-Pyroelectric-Infrared-PIR-module-Motion-Sensor-Detector-Module/32246786359.html

Se che sirven esos, eu teño unha pila deles.

Sensores Hall non teño, pero podería servirnos este:
http://tienda.bricogeek.com/sensores/514-sensor-de-efecto-hall-us1881.html

Sobre os LEDs non hai fallo, que seguro que tamén teño eu pila deles.

E protoboards seguramente tamén atoparemos algunhas por aí.

**Comment by braisarias** [comment]
Outra cuestión:
A pantalla, rato e teclado son imprescindibles?

**Comment by ResonantWave** [comment]
Si, esos PIR irán perfectos. Respecto a los sensores Hall, esos no valdrán, ya que son analógicos. En cambio se podría usar el [DRV5013ADQLPGM](https://store.ti.com/DRV5013ADQLPGM.aspx).

Por otro lado, la pantalla, ratón y teclado serían interesantes, aunque se puede hacer todo por ssh.

**Comment by ResonantWave** [comment]
Dejo aquí el repo en el que iré subiendo la [presentación y los contenidos de la charla](https://github.com/ResonantWave/charla-2).
