### ISSUE TITLE
Atopar lugar onde facer os Hackathons (No centro)

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#53]
- Estase falar co concello
  ¿Outras ideas? ¿Igual as oficinas de algunha empresa?

**Comment by castrinho8** [comment]
Estamos entre o Forum Metropolitano e o EIX, aínda por confirmar

**Comment by ssaavedra** [comment]
Quen ten que decidir? O Concello?

**Comment by castrinho8** [comment]
Estou a espera do concello sii, no forum as salas que nos deixan son para 20 persoas e así un pouco pechadas, a ver si nos deixaron o EIX...

**Comment by castrinho8** [comment]
Vou:
- Insistir nos lugares do concello
- Preguntar na Normal
- Como último recurso, a FIC

**Comment by txenoo** [comment]
- Se existe dispoñibilidade da sala de reunións que temos en Igalia na data do Hackaton podería consultar se é posible organizala nas nosas oficinas.

**Comment by castrinho8** [comment]
Pois sería unha proposta moi interesante, de momento estou a espera do concello e según a resposta que obteña, podemos ver esta opción ;)
