### ISSUE TITLE
Añadir un código de conducta

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#56]
Cómo todo evento técnico serio, creo que sería buena idea añadir un código de conducta, se que más gente lo ha comentado asique lo propongo aquí oficialmente ;)

**Comment by castrinho8** [comment]
Un código moi simple que collín do [Women Techmakers](http://wtm.gdgmadrid.es/code_of_conduct.html) de fai un par de semanas, ¿Cómo o vedes?

## Código de conducta

Requerimos que todos los asistentes, ponentes, patrocinadores y voluntarios de nuestra conferencia estén de acuerdo con el siguiente código de conducta.
La organización se encargará de que se cumpla durante el evento, esperamos la colaboración de todos los participantes para ayudar a construir un entorno seguro para todo el mundo.

### La versión rápida

Queremos que esta conferencia sea una experiencia libre de acoso para todo el mundo sin importar su género, su identidad o expresión de género, edad, orientación sexual, discapacidad, aspecto físico, raza o religión. No toleraremos el acoso de ningún tipo a ningún participante. 
El lenguaje o las imágenes sexuales no son apropiadas para el evento, incluyendo las charlas, Twitter y cualquier otro medio de comunicación.

Los participantes que violen estas reglas podrán ser sancionados o expulsados de la conferencia a discreción de los organizadores

### La versión no tan rápida

Incluímos como acoso los comentarios verbales ofensivos relacionados con el género, la identidad o expresión de género, edad, orientación sexual, discapacidad, apariencia física, raza, religión, imágenes sexuales en espacios públicos, intimidación deliberada, acecho, persecución, el acoso con fotografías o vídeos, la interrupción sostenida de charlas u otros eventos, el contacto físico inapropiado y la atención sexual indeseada. 

Los patrocinadores también se encuentran sujetos a esta política. En concreto, los patrocindores no deben usar imágenes, actividades u otro material sexualizado. El personal (incluyendo los voluntarios) no debe utilizar ropa/uniformes/disfraces sexualizados, o crear de ninguna otra forma un entorno sexualizado.

Si un participante tiene un comportamiento de acoso, los organizadores de la conferencia podrán tomar cualquier acción que consideren apropiada, incluyento advertir al infractor o su expulsión de la conferencia.
Si estás siendo acosado, ves a alguien que lo está siendo o tienes alguna otra preocupación, por favor contacta con algún miembro de la organización inmediatamente.
Los miembros de la organización estarán encantados de ayudar a los participantes a contactar con la seguridad del sitio o la policía local, proveer escolta o asistir de otra manera para ayudar a quienes están siendo acosados a sentirse seguros durante la conferencia.
Valoramos tu asistencia. Esperamos que los participantes sigan estas reglas durante la conferencia.

Source and credit: http://wtm.gdgmadrid.es/code_of_conduct.html
Original source and credit: http://2012.jsconf.us/#/about & The Ada Initiative
Please help by translating or improving: http://github.com/leftlogic/confcodeofconduct.com
This work is licensed under a Creative Commons Attribution 3.0 Unported License

**Comment by castrinho8** [comment]
Se non hay  oposición, suboo a web maña ;)

**Comment by braisarias** [comment]
A min paréceme ben
