### ISSUE TITLE
Segunda charla Raspberry Pi

### ISSUE THREAD

**Issue by ResonantWave** [gpul-labs/roadmap#59]
Estaría bien organizar una segunda charla sobre Raspberry Pi si hubiera tiempo, que abarque sensores más avanzados, como por ejemplo sensores barométricos, de humedad e incluso algún DAC para tener entradas analógicas, y leer LDRs, sensores de temperatura y demás.

**Comment by castrinho8** [comment]
Yo por mi encantado!! Se me ocurre igual la posibilidad de aprovechar el día que hagamos el primer hackathon y dar a lo mejor 2 horas de  todo esto antes de ponerse a currar con ello, ¿que te parece?

En cuanto a la fecha del hackathon, pensamos en el sábado día 19 de Marzo, cómo lo veis todos?

**Comment by ResonantWave** [comment]
Suena estupendo! Puedo preasumir que habrá al menos un proyector para unas pocas diapositivas? O dependerá del sitio donde se realice el hackaton?

**Comment by castrinho8** [comment]
Sisi, por eso no habrá problema ;)

**Comment by castrinho8** [comment]
Como ves la fecha del sábado 2 de Abril  @ResonantWave ?

**Comment by ResonantWave** [comment]
Perfecto, creo que no habrá ningún problema con la fecha

**Comment by castrinho8** [comment]
Al final hemos tenido que mover la fecha del hackathon al día 9 ya que el 2 es el arduino day  en lugo, te va bien la fecha @ResonantWave ?
