### ISSUE TITLE
Preguntar créditos de libre

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#6]
Ver si es posible que la UDC conceda créditos de libre

**Comment by castrinho8** [comment]
No decanato van preguntar ao reitorado que é quen leva ahora o tema e xa me avisan

**Comment by castrinho8** [comment]
- Para titulaciones antiguas: Hay que esperar al 1 de marzo
- Para Grado: Esperar a la convocatoria de subvenciones para asociaciones y preguntar ahi

**Comment by ssaavedra** [comment]
Qué significa esto?

**Comment by castrinho8** [comment]
Basicamente que paso de pedilo, non o podemos pedir como minimo hasta que se resolvan as axudas da udc e buuu, vai ser un rollo de papelos para a pouca utilidade que tera
