### ISSUE TITLE
Charla 5 - Django: Voluntarios

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#60]

**Comment by Uxio0** [comment]
Boas xente!

Non sei se é o lugar adecuado, pero quería preguntarvos se tedes algunha preferencia para orientar a charla de Django. En principio polo que falei con Brais a miña idea era usar varias Raspberries, e programar un pequeno módulo nelas para poder ler sensores e que os datos vaian para unha web con Django.

Como o vedes? Preferides outra cousa?

Saúdos

**Comment by castrinho8** [comment]
Boas uxío, mesmamente vale esta issue.

Eu penso que pode ser unha boa idea pero tampouco te compliques moito co tema das Raspberrys, con tal de mostrar que é sinxelo integrar a recollida de datos e logo ver un pouco as cousas que facer con Django e os diversos módulos que poden ser interesantes ;)

**Comment by Uxio0** [comment]
Ok!
