### ISSUE TITLE
Propostas para ampliar temática.

### ISSUE THREAD

**Issue by daavoo** [gpul-labs/roadmap#70]
Ola! Son David, que estaba na edición de Yuzz do ano pasado e na II de GOF cun proxecto de drons.

Primeiro noraboa pola iniciativa aínda que me jode un pouco que tras 5 anos que levo en Coruña e xusto colledes e montades o tema este cando me mudo a Vigo. xD

Estiven vendo a temática das charlas e quería propoñeros ampliar un pouco a temática por exemplo metendo un pouco de visión artificial (cos bindings para python de opencv ou coa librería scikit-image) e tamén de aplicacións para drons (coa api de python de dronekit por exemplo).

Penso que molaría moito meter estes temas e facer un último proxecto aplicando toda a temática das charlas así en plan locura (que non é tanta locura, que é facil facelo, que o fixen eu e eu fai un ano non sabía programar nada) como por exemplo manexar un dron cunha raspberry (co dronekit por exemplo), e que mentras voa grabando un vídeo, se aparece algo vermello (ou algo con forma redonda, ou algo...) no campo de visión da cámara (detectándoo con opencv por exemplo) colla eses frames nos que aparece a cousa vermella e o suba (coa api rest de dronekit por exemplo) a unha plataforma web (feita con django por exemplo).

Bueno, pois esa é a idéa. xD. Non sei se xa é moita temática para ampliar pero penso que encaixa co que estades a dar de momento e que penso que molaba xente fixera entre todos aplicando o que aprenderon nas charlas o proxecto que vos dixen ou algo así.

Eu podería facilitaros se queredes  tutoriales feitos en notebooks de Jupyter (que por certo tambén creo que sería interesante tratalos) que estou a facer sobre opencv e scikit-image. E tamén ando a fozar coa api de dronekit e podería mandaros algún material.

Un saúdo e moita sorte!

Falamos

**Comment by ssaavedra** [comment]
Ola David,

Unha mágoa que te mudases este ano. Todo estaría ben telo feito antes, pero
precisamente nisto consiste o futuro: en facer cousas que antes non
faciamos, unha mágoa non poder ir ao futuro máis rápido :-)

O que comentas é unha idea fantástica, e de feito sería sensacional poder
rematar con outro proxecto/spin-off/ así un pouco máis complexo ca o que
podemos chegar a xerar co día á semana que temos para vernos.

Se ti ou alguén que coñeces ten o tempo para conducir esta actividade,
podemos ver como xestionalo.

Non sei aínda como podemos xestionalo pero supoño que podería dar máis
aproveitamento se puidese ser nunha fin de semana algo tipo hackaton?
@gpul-labs/coordinacion que opinades?

Por suposto, que aínda que esteas en Vigo, para estas cousas aínda que non
podemos evitarche o custe en tempo do desprazamento sí que lles libramos
aos voluntarios do económico, que xa abondo é o feito de vir desde Vigo,
sabendo que o que mola está en Coruña :-P

Un saúdo!

**Comment by daavoo** [comment]
Paréceme unha gran idea o de facelo en plan hackatón.

Eu podo ter tempo para axudarvos a conducir a actividade pero agora mesmo ando algo liado, se o querríades facer de mediados de Abril en adiante entón podería sen problemas.

Penso que unha boa estructura sería:

Facer dúas charlas previas a hackatón sobre:
- Visión Artificial con python (Quizáis mellor scikit-image ca opencv, por ser a primeria "puro" python e a outra "só" bindings a c++)
- Apps para drons (Ahí sen dúbida a mellor opción paréceme Dronekit)

Persoalmente non creo que puidese dar as charlas previas ao hackatón destas temática pero  se alguén da organización se ofrece, eu sen problema lle facilitaría os tutoriais que teño feitos e que él organice a charla.

Quizás tamén estas dúas temáticas serían demasiado "profundas" para o tempo dunha charla, e podería se eso facilitarse material de cada tema en plan "deberes opcionais da semana pa facer na casa". (Este material si que podría facilitárvolo sen problema)

E logo de estas dúas charlas organizar algo rollo hackatón (que se é un fin de semana eu falo coa miña moza e imos pode que me deixe e todo, xD, e olvídate de que paguedes o desprazamento que iso págomo eu e encantado) no que o primeiro día pola mañá podría ser o mítico de unhas charlas máis "pro" con consellos para os grupos da hackatón (eu podería dar os consellos de visión artificial e da parte de apps de onboard computing, pero as api rest e desarrollo de aplicacións web xa mellor que as de outro) e logo que se mate a peña a aporrear o teclado e o domingo presentar os proxectos de cada grupo.

Penso que sería relativamente fácil de organizar no sentido de que a temática "fai algo en python que manexe un dron e realice algunha taréa de visión artificial mentres vóa e se comunique cunha web" da para moitas ideas de dios, e que con darlle unha raspberry a cada un dos grupos e ter un único dron o día das presentacións pra facer a demostración de cada aplicación xa vai que chuta.

Ademáis toda a carallada de drons e tal está de hype máximo e penso que conseguir patrocinios para a hackatón sería, dentro do que cabe, doado. 

Non sei que vos parecería a estructura así. Eu para o que queirades axúdovos

**Comment by castrinho8** [comment]
Boas David, encantado de volver a verte :)

Ahora que o comentas, xusto este mércores tamén se falou de usar OpenCV nun proxecto para control de afogamentos en piscinas con análise de imaxes cunha raspberry!

A idea é polo menos facer **un par de hackathones**, o primeiro casi seguro que será o **día 2 de Abril** para ir abrindo boca, propoñendo proxectos con temas de IoT e empezar a cacharrear algo, e fijo que o tema dos drones encaixa cojonudo, xa che digo, se te queres apuntar invitado estás e igual se controlas de algún destes temas, igual te podes apuntar a dar unha charla o mesmo dia sobre el ;)
De feito, @ResonantWave falará sobre leer sensores un pouco máis potentes coa Raspberry asique molaría mogollón poder contar con algo así tamén jeje

E o segundo hackathon, aínda estamos pendientes de diversos temas pero é probable que sexa o finde do **30 de Abril** xa que non se pode retrasar moito porque empezan os exámenes.

**Comment by daavoo** [comment]
Boas Pablo, encantado tamén e de ver que andas a tope.

OpenCv pétao moito, aínda que non sei por qué (supoño que tampouco poden andar a todo) aínda hay varias cousas (de feito moitas das más molonas) que non teñen "wrapeadas" en Python. Eu estou a usar scikit-image e scikit-learn combinadas e, aínda que é máis coñazo, poder pódese suplir as cousas que faltan nos bindings de opencv para Python.

Case fixo que a do 2 de Abril non poida, pero á segunda pode que si.

Sorte con isto.

**Comment by ssaavedra** [comment]
Comento aquí que se moveu esa data do 2 ao 9.
