### ISSUE TITLE
Normalizar nombres de carpetas con documentación de charlas

### ISSUE THREAD

**Issue by ssaavedra** [gpul-labs/roadmap#71]
Agora mesmo hai dúas carpetas, unha `charla_1` e `charla_3` mentres que `charla-2` está escrita empregando un guión en lugar dun guión baixo. Esto da lugar a unha ordenación lexicográfica errónea co nome das carpetas.

Sería conveniente mover `charla-2` a `charla_2` ou ben escoller outro esquema co que chamarlle ás carpetas.

**Comment by ResonantWave** [comment]
Ya que predomina el formato de charla_n, ya me encargo de cambiar charla-2 a charla_2

**Comment by ResonantWave** [comment]
Listo!
