### ISSUE TITLE
Enviar difusión hackathon

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#73]
Enviar email con nota de prensa a diversos medios para publicitar el evento.
(mancomun, codigo cero, digest, udc, fic...)

**Comment by ssaavedra** [comment]
Está redactada a NdP?

Podemos usar o foro, a wiki daquí, ou o etherpad. Etherpad?

**Comment by castrinho8** [comment]
Mais que unha nota de prensa, teño un simple email que penso que pode valer (ira con diversas urls que ahora non podo pegarlle xD):

Bos días,

Dende a asociación GPUL continuamos a promocionar o software e o hardware libre a través da nosa actividade, os GPUL Labs que están a ter unha gran acollida e repercusión no entorno tecnolóxico galego.

É por isto que nos gustaría anunciar que xa temos publicado unha nova remesa de actividades, todas ao redor dun proxecto baseado en tecnoloxías libres, así como un primeiro hackathon de desenvolvemento sobre IoT no que os asistentes desenvolverán pequenos prototipos durante un día de traballo colaborativo.

A entrada é totalmente gratuita, os asistentes disporán de hardware para desenvolver o seu proxecto como Raspberrys, Arduinos e sensores para facer probas e por suposto invitaremolos a almorzar e comer, todo co obxectivo de facer piña e crear unha comunidade de desenvolvedores preocupados polas tecnoloxías libres que impulsen proxectos de código aberto.

Un saúdo!
