### ISSUE TITLE
Conseguir material para Hackathon

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#84]
Ver si podemos conseguir cousas, tipo sensores, arduinos ou outra cacharrada que poida ser interesante

**Comment by castrinho8** [comment]
@braisarias , sabes algo do rapaz de bricogeek? Se non igual se podería falar con bricolabs ou con alguén, non?

**Comment by braisarias** [comment]
Nada, non sei nada máis, vou volver chamalo ou algo, porque senón...

2016-03-28 19:23 GMT+02:00 Pablo Castro notifications@github.com:

> @braisarias https://github.com/braisarias , sabes algo do rapaz de
> bricogeek? Se non igual se podería falar con bricolabs ou con alguén, non?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gpul-labs/roadmap/issues/84#issuecomment-202495186

## 

Brais Arias Rio

**Comment by braisarias** [comment]
Nada, non sei nada máis, vou volver chamalo ou algo, porque senón...
Habería que ver que nos fai falla.

**Comment by castrinho8** [comment]
Algunhas ideas sobre algunhas cousas que igual se podían conseguir a parte dos sensores que xa temos (son ideas, se se consigue algo ben, se non non pasa nadaa)
- GPS
- sensor temperatura
- acelerometro
- giroscopio
- camara video
- RFID con algún 
  ....
