### ISSUE TITLE
Lightning talks

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/roadmap#92]
Montar 3 ou 4 charlas rápidas de 10 mins ou así sobre cousas básicas no hackathon para a xente que igual nunca estivo en algo así.
- Agile práctico con waffle e github ou con https://taiga.io/
- Git basiquísimo + github
- Sensores avanzados para raspberry (igual esta pode ser un pelin mais larga)
- Ventaxas de liberar o proxecto e modelos de negocio libres

**Comment by castrinho8** [comment]
Cómo o vedes? Alguén se apunta?
Eu podo contar a última e se ven Javi igual pode contar a penúltima

**Comment by ssaavedra** [comment]
Eu apuntome a github e incluso a coordinar o repo durante o hackatón, vou crear issues para iso.
